### ISSUE TITLE
move search bar to left nav

### ISSUE THREAD

**Issue by MrBiscuit921** [sanoojes/spicetify-extensions#2]
![image](https://github.com/user-attachments/assets/4fe3e584-ee65-47ed-888b-4c34206b8356)

**Comment by sanoojes** [comment]
The search bar was initially positioned on the side, but this placement negatively impacted search functionality and other features. Therefore, I relocated it to the top.

**Comment by sanoojes** [comment]
While the current implementation is functional, maintaining this approach would likely introduce search functionality bugs in the future. To address this and provide user flexibility, I plan to incorporate settings that allow for customizable positioning of elements like the search bar and sidebar.

Old screenshots
![image](https://github.com/user-attachments/assets/6320c182-e228-4ea8-89be-9b7d64b4be90)
![image](https://github.com/user-attachments/assets/7af26b84-a39b-4374-80c4-7f4097086176)

**Comment by owen-the-kid** [comment]
i do like this idea but i would like a switch to choose between on the top or in the bar

**Comment by sanoojes** [comment]
> i do like this idea but i would like a switch to choose between on the top or in the bar

yes thats good but the search becomes buggy when i put it there 
will be checking out on this soon

**Comment by LookedSpy637832** [comment]
> > i do like this idea but i would like a switch to choose between on the top or in the bar
> 
> yes thats good but the search becomes buggy when i put it there will be checking out on this soon

Any updates?

**Comment by sanoojes** [comment]
> > > i do like this idea but i would like a switch to choose between on the top or in the bar
> > 
> > 
> > yes thats good but the search becomes buggy when i put it there will be checking out on this soon
> 
> Any updates?

Nope i have exams goin on rn so it will get late unless a dev helps on it

**Comment by sanoojes** [comment]
Add this snippet and you are good to go for now.
@LookedSpy637832 @MrBiscuit921 

Marketplace => snippets => add css => paste this code 
```css
.Root__globalNav .fmZ0hU6ImbDQi5qGWLvF, .Root__globalNav .main-globalNav-searchContainer>span:nth-child(2), .Root__globalNav .main-globalNav-searchContainer>span[role='presentation'], .Root__globalNav .main-globalNav-searchContainer>.zugTpa7GhjPIQmTCgBzw, .Root__globalNav .main-globalNav-searchContainer .main-globalNav-searchInputSection, .Root__globalNav .main-globalNav-searchContainer>form{
  position: relative !important;
  inset: 0 !important;
}
.Root__globalNav{
    overflow: visible;
}
.searchInputCollapsed ._b3hhmbWtOY8_1M1mM1H>.b7r2WRiu5f9Q99qmyreh {
  width: 100% !important;
}

.searchInputCollapsed ._b3hhmbWtOY8_1M1mM1H>.b7r2WRiu5f9Q99qmyreh>:last-child {
  opacity: 1 !important;
  visibility: visible !important;
}

.searchInputCollapsed ._b3hhmbWtOY8_1M1mM1H>.b7r2WRiu5f9Q99qmyreh .MdMAXXFPalD99eigsBug {
  display: initial !important;
}
```
