### ISSUE TITLE
[feature request] Highlight the title of the song is playing

### ISSUE THREAD

**Issue by ChrisVineyard-abc** [sanoojes/spicetify-extensions#6]
I hope you add a customizable color highlight for the title of the song that's playing in your theme.

![Screenshot 2024-09-29 203759](https://github.com/user-attachments/assets/104ffe63-d0c9-4f66-b7b8-cd2432df9c4a)

**Comment by sanoojes** [comment]
You can change the color to any value you want. Replace `rgba(255,255,255,1)` with your desired color value.

```css
.main-trackList-trackListRow.main-trackList-active .main-trackList-rowTitle, .main-trackList-trackListRow.main-trackList-active .main-trackList-rowMarker {
    color: rgba(255,255,255,1) !important;
}
```

Also, please consider reporting theme-related issues in the theme repository, not the extensions repository. 
Link to Theme repo: https://github.com/sanoojes/Spicetify-Lucid
