### ISSUE TITLE
How to move the libx to right sidebar

### ISSUE THREAD

**Issue by harsharora08** [sanoojes/spicetify-extensions#8]
I use a custom CSS that switches the sidebars, so the libx now appears on the top of now playing bar. How can I make it appear on the right sidebar?

![image](https://github.com/user-attachments/assets/e16760f2-9e74-4b82-8bab-426ce1158f4b)

Thank you for the extension

**Comment by sanoojes** [comment]
> I use a custom CSS that switches the sidebars, so the libx now appears on the top of now playing bar. How can I make it appear on the right sidebar?
> 
> ![image](https://private-user-images.githubusercontent.com/41362690/372987943-e16760f2-9e74-4b82-8bab-426ce1158f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4OTgzMzksIm5iZiI6MTcyNzg5ODAzOSwicGF0aCI6Ii80MTM2MjY5MC8zNzI5ODc5NDMtZTE2NzYwZjItOWU3NC00YjgyLThiYWItNDI2Y2UxMTU4ZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE5NDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3Mzk5MWZiNjIxMjE2NGViNWY4YWM0YmUzYzAyODIyNzc2NmIyNTk5NTlkZWVhMDE1NzU5MTExODY2MjVmMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PlVbl0GSZJJTvgb1zZajeMw3udVUKGfVw6YkQuQaJK0)
> 
> Thank you for the extension

can you give the snippet so i can modify it and give you the modified snippet ?

**Comment by sanoojes** [comment]
you can add this snippet to move it to left

```css
.Root__top-container, :root .global-nav .Root__top-container, .spotify__container--is-desktop .global-nav .Root__top-container{
    grid-template-areas: "right-sidebar main-view global-nav" 
"right-sidebar main-view left-sidebar"
"now-playing-bar now-playing-bar now-playing-bar" !important
}
```
